print("\n+++++++++++++++++++++++++++++++++")
print("This Is Mad lib Game")
print("+++++++++++++++++++++++++++++++++\n")
print("Roses are _____")
print("______ are blue")
print("I love _______")
print("\n+++++++++++++++++++++++++++++++++\n")

color = input("Enter a color : ")
plural_noun = input("Enter a plural_noun : ")
clebrity = input("Enter a clebrity : ")
print("\n+++++++++++++++++++++++++++++++++\n")
print("Roses are "+color+"")
print(""+plural_noun+ " in blue")
print("I love "+colorlebrity+"")